// A recorded-shape fixture of the seeded double-booking investigation.
// It exists so you can check the deployment end to end before the agent
// runtime is connected. Runs created from it are marked "simulated" and the
// room says so. It is never mixed into a real run.

const m = (from, to, type, refs, body, extra = {}) => ({ kind: "message", from, to, type, refs, body, ...extra });
const l = (from, record, id, value) => ({ kind: "ledger", from, data: { record, id, value } });
const t = (from, tool, summary, status = "ok") => ({ kind: "tool", from, data: { tool, summary, status } });
const b = (from, session_id, status, env, env_detail, run, outcome) => ({ kind: "browser", from, data: { session_id, status, provider: session_id.startsWith("local") ? "local" : "browserbase", env, env_detail, experiment: "EXP-3", run, target: "booking-app (main)", outcome } });
const s = (stage, reason, refs = []) => ({ kind: "stage", from: "incident-lead", data: { stage, reason, refs } });

export const DEMO_TRACE = [
  { delay: 400, event: { kind: "system", type: "RUN_STARTED", body: "Investigate these complaints and open a reviewable fix for any confirmed defect. 18 tickets, 3 screenshots, 1 log export." } },
  { delay: 900, event: t("support-engineer", "tickets", "Reading 18 tickets and 3 screenshots", "start") },
  { delay: 600, event: t("sre-analyst", "logs", "Blind pass over booking-service logs, 14 days", "start") },
  { delay: 1400, event: l("support-engineer", "claim", "CLM-001", { statement: "Pressed Book once and has two reservations.", source: { kind: "customer", ref: "T-01" }, status: "reported", missing_fields: ["device", "app_version"] }) },
  { delay: 500, event: l("support-engineer", "claim", "CLM-004", { statement: "Only happens on my phone.", source: { kind: "customer", ref: "T-02" }, status: "reported", missing_fields: ["browser", "network"] }) },
  { delay: 500, event: l("support-engineer", "claim", "CLM-009", { statement: "Duplicate booking issue was fixed last week. Probably user error.", source: { kind: "support_note", ref: "T-07", author: "support colleague" }, status: "reported" }) },
  { delay: 500, event: l("support-engineer", "claim", "CLM-016", { statement: "Got two confirmation emails.", source: { kind: "customer", ref: "T-14" }, status: "reported", contradicts: ["CLM-017"] }) },
  { delay: 400, event: l("support-engineer", "claim", "CLM-017", { statement: "Account A-2291 holds exactly one reservation for that slot.", source: { kind: "db", ref: "T-14" }, status: "observed", contradicts: ["CLM-016"] }) },
  { delay: 900, event: l("sre-analyst", "claim", "CLM-021", { statement: "7 accounts show two POST /bookings with identical payload 2.1-3.9s apart, both 201.", source: { kind: "log", ref: "query q-03" }, status: "observed", evidence: ["artifacts/reports/q-03.json"] }) },
  { delay: 500, event: l("sre-analyst", "claim", "CLM-022", { statement: "41% of booking requests carry no correlation ID; joined on account + payload hash + time window.", source: { kind: "log", ref: "query q-04" }, status: "observed" }) },
  { delay: 500, event: l("sre-analyst", "claim", "CLM-023", { statement: "Last week's deploy touched BookButton.tsx only. No server or fetch-wrapper change.", source: { kind: "log", ref: "deploy d-118" }, status: "observed" }) },
  { delay: 700, event: m("support-engineer", ["incident-lead"], "HANDOFF", ["T-01", "T-18", "CLM-001", "CLM-016"], "18 tickets, 31 claims. 2 contradictions recorded, 3 tickets have no usable identifiers. T-07 'already fixed' is a colleague's assertion, kept as reported.") },
  { delay: 600, event: m("sre-analyst", ["incident-lead"], "HANDOFF", ["CLM-021", "CLM-022", "CLM-023"], "Server sees clean 201s. No errors anywhere. The anomaly is paired identical writes. A lost response would look exactly like this from the server side.") },
  { delay: 900, event: s("S1", "Both intake handoffs received") },
  { delay: 900, event: l("incident-lead", "incident", "INC-1", { title: "Duplicate reservations from a single booking attempt", tickets: ["T-01", "T-02", "T-04", "T-05", "T-09", "T-11", "T-12"], match_basis: "account_id+reservation_id", status: "open" }) },
  { delay: 500, event: l("incident-lead", "incident", "INC-2", { title: "Duplicate confirmation emails, single reservation", tickets: ["T-14"], match_basis: "account_id", status: "open", excluded_from: "INC-1: two emails, one reservation" }) },
  { delay: 700, event: l("incident-lead", "hypothesis", "HYP-1", { incident: "INC-1", statement: "User double-clicks Book.", predicts: "Two rapid clicks create two rows", would_be_refuted_by: "Second click is blocked", status: "proposed" }) },
  { delay: 400, event: l("incident-lead", "hypothesis", "HYP-2", { incident: "INC-1", statement: "It is the browser, not the website: mobile browsers only.", predicts: "Fails on phone browsers, not on desktop or in a clean cloud browser", would_be_refuted_by: "Same result on every engine", status: "proposed" }) },
  { delay: 400, event: l("incident-lead", "hypothesis", "HYP-3", { incident: "INC-1", statement: "Client auto-retries after a lost response; server is not idempotent.", predicts: "1 click + dropped response gives 2 rows on any browser", would_be_refuted_by: "Dropped response gives 1 row", status: "proposed" }) },
  { delay: 700, event: s("S2", "Every hypothesis has a falsifiable experiment", ["HYP-1", "HYP-2", "HYP-3"]) },
  { delay: 500, event: m("incident-lead", ["qa-engineer"], "EXPERIMENT_REQUEST", ["HYP-1", "HYP-2", "HYP-3"], "Run the dropped-response experiment on desktop and mobile first. It splits HYP-2 and HYP-3 in one go. Then double-click as a control.") },
  { delay: 600, event: m("sre-analyst", ["qa-engineer"], "NOTE", ["CLM-021"], "Gap between paired writes clusters at 3s. That smells like a fixed client retry delay, not a human. Try aborting the response, not the request.", { cc: ["incident-lead"] }) },
  { delay: 900, event: t("qa-engineer", "playwright", "EXP-1 double-click, 3 runs from reset state", "start") },
  { delay: 1600, event: l("qa-engineer", "experiment", "EXP-1", { hypothesis: "HYP-1", conditions: { clicks: 2, network: "clean" }, observed: "1 reservation (3/3). Button disabled after first click.", outcome: "refutes", runs: 3, artifacts: ["artifacts/traces/exp1.zip"] }) },
  { delay: 600, event: t("qa-engineer", "browser lab", "Cloud browser session dropped before the first click", "error") },
  { delay: 500, event: m("qa-engineer", ["incident-lead"], "BLOCKED_INFRA", [], "The cloud browser session dropped before the click. Not product behaviour. Rerunning; nothing written to the ledger.") },
  { delay: 1200, event: t("qa-engineer", "browser lab", "EXP-3: same steps in 7 environments, 3 runs each. Browserbase cloud Chromium plus local Safari and Firefox engines", "start") },
  { delay: 700, event: b("qa-engineer", "bb-sim-01", "open", "Cloud Chromium, desktop", "chromium, 1440x900, clean network", 1) },
  { delay: 900, event: b("qa-engineer", "bb-sim-01", "closed", "Cloud Chromium, desktop", "chromium, 1440x900, clean network", 1, "Behaved correctly") },
  { delay: 600, event: b("qa-engineer", "bb-sim-02", "open", "Cloud Chromium, desktop, lost response", "chromium, 1440x900, drop response", 1) },
  { delay: 1000, event: b("qa-engineer", "bb-sim-02", "closed", "Cloud Chromium, desktop, lost response", "chromium, 1440x900, drop response", 1, "Failure reproduced") },
  { delay: 600, event: b("qa-engineer", "local-sim-03", "open", "Safari engine, iPhone", "webkit, iPhone 14, drop response", 1) },
  { delay: 1000, event: b("qa-engineer", "local-sim-03", "closed", "Safari engine, iPhone", "webkit, iPhone 14, drop response", 1, "Failure reproduced") },
  { delay: 1200, event: l("qa-engineer", "experiment", "EXP-3", { hypothesis: "HYP-3", conditions: { clicks: 1, environments: 7 }, expected_if_true: "2 reservations whenever the response is lost, on every engine; 1 on a clean network", observed: "12/21 runs failed: every lost-response run, no clean-network run", outcome: "supports", runs: 21,
      matrix: [
        { env: "Cloud Chromium, desktop", provider: "browserbase", fault: "none", runs: 3, failed: 0, infra: 0 },
        { env: "Cloud Chromium, desktop, lost response", provider: "browserbase", fault: "drop response", runs: 3, failed: 3, infra: 0 },
        { env: "Cloud Chromium, phone size, lost response", provider: "browserbase", fault: "drop response", runs: 3, failed: 3, infra: 0 },
        { env: "Safari engine, iPhone", provider: "local", fault: "drop response", runs: 3, failed: 3, infra: 0 },
        { env: "Firefox, desktop", provider: "local", fault: "drop response", runs: 3, failed: 3, infra: 0 },
        { env: "Safari engine, iPhone, clean", provider: "local", fault: "none", runs: 3, failed: 0, infra: 0 },
        { env: "Cloud Chromium, ad blocking", provider: "browserbase", fault: "none", runs: 3, failed: 0, infra: 0 },
      ],
      attribution: { verdict: "website_defect_network_trigger", because: "Fails in a clean cloud browser and on every engine tested (chromium, firefox, webkit), only when the network misbehaves. Not the customer's browser." },
      artifacts: ["artifacts/tests/repro/lost_response.spec.ts"] }) },
  { delay: 500, event: l("qa-engineer", "claim", "CLM-001", { status: "observed", evidence: ["EXP-3"] }) },
  { delay: 500, event: m("qa-engineer", ["incident-lead"], "EXPERIMENT_RESULT", ["EXP-1", "EXP-3", "HYP-2", "HYP-3"], "HYP-3 supported, HYP-1 refuted. It is the website, not the browser: a clean cloud Chromium with no extensions or cache fails exactly like Safari and Firefox, and only when the response is lost. 'Mobile only' is a reporting artefact: phones lose responses more often. Failing test committed; it fails on main.", { cc: ["sre-analyst"], artifacts: ["artifacts/tests/repro/lost_response.spec.ts"] }) },
  { delay: 900, event: m("sre-analyst", ["qa-engineer"], "INFO_RESPONSE", ["EXP-3", "CLM-021", "INC-1"], "Your trace matches production for 6 of 7 INC-1 tickets. T-11 has no logs in the window, so it cannot be checked either way.", { cc: ["incident-lead"] }) },
  { delay: 800, event: l("incident-lead", "hypothesis", "HYP-3", { status: "supported", experiments: ["EXP-3"] }) },
  { delay: 300, event: l("incident-lead", "hypothesis", "HYP-2", { status: "refuted", experiments: ["EXP-3"] }) },
  { delay: 300, event: l("incident-lead", "hypothesis", "HYP-1", { status: "refuted", experiments: ["EXP-1"] }) },
  { delay: 500, event: l("incident-lead", "incident", "INC-1", { status: "confirmed_defect", unresolved_tickets: ["T-11"] }) },
  { delay: 700, event: s("S3", "Failing regression test exists on main", ["EXP-3"]) },
  { delay: 500, event: m("incident-lead", ["software-engineer", "release-verifier"], "TASK", ["INC-1", "HYP-3", "EXP-3"], "Engineer: patch from the failing test. Verifier: write acceptance tests for the invariant now, before any patch exists.") },
  { delay: 1500, event: t("release-verifier", "git", "Committed 4 protected tests: lost response, delayed retry, concurrent retry, two genuine bookings", "ok") },
  { delay: 1800, event: l("software-engineer", "patch", "PATCH-1", { incident: "INC-1", branch: "fix/inc-1-disable-on-submit", root_cause: "Book button can fire twice; BookButton.tsx:41", diff_path: "artifacts/patches/patch1.diff" }) },
  { delay: 500, event: m("software-engineer", ["release-verifier"], "HANDOFF", ["PATCH-1", "INC-1"], "Disables the button and debounces submit for 5s.") },
  { delay: 700, event: s("S4", "Patch submitted", ["PATCH-1"]) },
  { delay: 1600, event: l("release-verifier", "verdict", "VER-1", { patch: "PATCH-1", regression_fails_on_base: true, regression_passes_on_branch: false, existing_suite: "pass", result: "rejected" }) },
  { delay: 500, event: m("release-verifier", ["software-engineer"], "COUNTEREXAMPLE", ["PATCH-1", "VER-1", "EXP-3"], "One click, response dropped, still two reservations. The retry comes from the fetch wrapper, not the button. Failing test attached. The server owns this invariant.", { cc: ["incident-lead"], artifacts: ["tests/protected/lost_response.spec.ts"], requires_response: true }) },
  { delay: 900, event: s("S3", "Counterexample against PATCH-1", ["VER-1"]) },
  { delay: 900, event: m("software-engineer", ["sre-analyst"], "INFO_REQUEST", ["PATCH-1", "CLM-022"], "Does anything in front of booking-service strip custom headers? I want to send an Idempotency-Key from the client.") },
  { delay: 900, event: m("sre-analyst", ["software-engineer"], "INFO_RESPONSE", ["CLM-022"], "No. The edge proxy passes unknown headers through. Correlation IDs go missing because the mobile client never sets them, not because they are stripped.") },
  { delay: 2000, event: l("software-engineer", "patch", "PATCH-2", { incident: "INC-1", branch: "fix/inc-1-idempotent-booking", supersedes: "PATCH-1", root_cause: "POST /bookings is not idempotent (bookings/create.ts:88) and lib/fetch.ts:23 retries on network error.", diff_path: "artifacts/patches/patch2.diff", addresses_counterexamples: ["VER-1"] }) },
  { delay: 500, event: m("software-engineer", ["release-verifier"], "HANDOFF", ["PATCH-2", "VER-1"], "Client sends one Idempotency-Key per booking attempt; server stores it with a unique constraint and returns the original reservation on replay. Two separate attempts get two keys.") },
  { delay: 700, event: s("S4", "Revised patch submitted", ["PATCH-2"]) },
  { delay: 1200, event: t("release-verifier", "playwright", "Protected suite + 2 new attacks: replayed key with changed payload, key reuse across accounts", "start") },
  { delay: 2200, event: l("release-verifier", "verdict", "VER-2", { patch: "PATCH-2", regression_fails_on_base: true, regression_passes_on_branch: true, existing_suite: "pass", adversarial_cases: [{ name: "two genuine bookings still create two rows", result: "pass" }, { name: "same key, different payload is refused", result: "pass" }, { name: "key cannot be replayed across accounts", result: "pass" }], result: "verified" }) },
  { delay: 500, event: m("release-verifier", ["incident-lead"], "VERDICT", ["VER-2", "PATCH-2"], "Verified in sandbox. Fails on main, passes on branch, existing suite green, five adversarial cases pass.", { cc: ["software-engineer"] }) },
  { delay: 500, event: l("incident-lead", "incident", "INC-1", { status: "fix_verified" }) },
  { delay: 400, event: l("incident-lead", "incident", "INC-2", { status: "insufficient_evidence", needs: ["email provider message IDs for T-14"] }) },
  { delay: 700, event: s("S5", "Verdict VER-2 is verified", ["VER-2"]) },
  { delay: 900, event: { kind: "approval", from: "software-engineer", data: { id: "APR-1", title: "Open draft pull request for PATCH-2", detail: "fix/inc-1-idempotent-booking into main. 3 files, +64 -9. Links INC-1, HYP-3, EXP-3, VER-2. States: fix proposed, not deployed.", refs: ["PATCH-2", "VER-2"] } } },
  { delay: 900, event: { kind: "approval", from: "support-engineer", data: { id: "APR-2", title: "Send 8 customer replies", detail: "6 tickets: 'We reproduced this and a fix is in review.' T-11: asks for booking time and device. T-14: explains one reservation exists, asks for the second email's headers.", refs: ["INC-1", "INC-2"] } } },
  { delay: 600, event: m("incident-lead", ["human"], "APPROVAL_REQUEST", ["APR-1", "APR-2", "INC-1"], "Investigation complete. Two actions are waiting for you. Nothing has been merged, deployed or sent.") },
];
